=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::BankAccountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BankAccountApi' do
  before do
    # run before each test
    @instance = Beanie::BankAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankAccountApi' do
    it 'should create an instance of BankAccountApi' do
      expect(@instance).to be_instance_of(Beanie::BankAccountApi)
    end
  end

  # unit tests for add_bank_account
  # Creates a new bank account in the system
  # @param bank_account Bank account to add to the system
  # @param [Hash] opts the optional parameters
  # @return [BankAccount]
  describe 'add_bank_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_bank_account_by_id
  # Find Bank Account by ID
  # Returns a single bank account if the user has access
  # @param id ID of bank account to fetch
  # @param [Hash] opts the optional parameters
  # @return [BankAccount]
  describe 'find_bank_account_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_bank_accounts
  # All bank accounts
  # Returns all bank accounts from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit maximum number of results to return
  # @return [Array<BankAccount>]
  describe 'find_bank_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
