=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::BeanieTaskApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BeanieTaskApi' do
  before do
    # run before each test
    @instance = Beanie::BeanieTaskApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BeanieTaskApi' do
    it 'should create an instance of BeanieTaskApi' do
      expect(@instance).to be_instance_of(Beanie::BeanieTaskApi)
    end
  end

  # unit tests for add_beanie_task
  # Creates a new beanie task in the system
  # @param beanie_tasks Beanie task to add to the system
  # @param [Hash] opts the optional parameters
  # @return [BeanieTask]
  describe 'add_beanie_task test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_beanie_task_by_id
  # Find Beanie task by ID
  # Returns a single beanie task if the user has access
  # @param id ID of beanie task to fetch
  # @param [Hash] opts the optional parameters
  # @return [BeanieTask]
  describe 'find_beanie_task_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_beanie_tasks
  # All beanie task
  # Returns all beanie task from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<BeanieTask>]
  describe 'find_beanie_tasks test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
