=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::BillableApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BillableApi' do
  before do
    # run before each test
    @instance = Beanie::BillableApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillableApi' do
    it 'should create an instance of BillableApi' do
      expect(@instance).to be_instance_of(Beanie::BillableApi)
    end
  end

  # unit tests for add_billable
  # Creates a new billable record in the system
  # @param billables Billable record to add to the system
  # @param [Hash] opts the optional parameters
  # @return [Billable]
  describe 'add_billable test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_billable_by_id
  # Find Billable record by ID
  # Returns a single billable record if the user has access
  # @param id ID of billable record to fetch
  # @param [Hash] opts the optional parameters
  # @return [Billable]
  describe 'find_billable_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_billables
  # All billable record
  # Returns all billable record from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<Billable>]
  describe 'find_billables test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
