=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::BillOfMaterialsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BillOfMaterialsApi' do
  before do
    # run before each test
    @instance = Beanie::BillOfMaterialsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillOfMaterialsApi' do
    it 'should create an instance of BillOfMaterialsApi' do
      expect(@instance).to be_instance_of(Beanie::BillOfMaterialsApi)
    end
  end

  # unit tests for add_bill_of_material
  # Creates a new bill of materials in the system
  # @param bill_of_materials Bill of Materials to add to the system
  # @param [Hash] opts the optional parameters
  # @return [BillOfMaterial]
  describe 'add_bill_of_material test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_bill_of_material_by_id
  # Find Bill of Materials by ID
  # Returns a single bill of materials if the user has access
  # @param id ID of bill of materials to fetch
  # @param [Hash] opts the optional parameters
  # @return [BillOfMaterial]
  describe 'find_bill_of_material_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_bill_of_materials
  # All bill of materials
  # Returns all bill of materials from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<BillOfMaterial>]
  describe 'find_bill_of_materials test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
