=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::CustomerAddressApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CustomerAddressApi' do
  before do
    # run before each test
    @instance = Beanie::CustomerAddressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CustomerAddressApi' do
    it 'should create an instance of CustomerAddressApi' do
      expect(@instance).to be_instance_of(Beanie::CustomerAddressApi)
    end
  end

  # unit tests for add_customer_address
  # Creates a new customer address in the system
  # @param customer_addresses Customer address to add to the system
  # @param [Hash] opts the optional parameters
  # @return [CustomerAddress]
  describe 'add_customer_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_customer_address_by_id
  # Find Customer address by ID
  # Returns a single customer address if the user has access
  # @param id ID of customer address to fetch
  # @param [Hash] opts the optional parameters
  # @return [CustomerAddress]
  describe 'find_customer_address_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_customer_addresses
  # All customer address
  # Returns all customer address from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<CustomerAddress>]
  describe 'find_customer_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
