=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::DeliveryNoteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DeliveryNoteApi' do
  before do
    # run before each test
    @instance = Beanie::DeliveryNoteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeliveryNoteApi' do
    it 'should create an instance of DeliveryNoteApi' do
      expect(@instance).to be_instance_of(Beanie::DeliveryNoteApi)
    end
  end

  # unit tests for add_delivery_note
  # Creates a new delivery note in the system
  # @param delivery_notes Delivery note to add to the system
  # @param [Hash] opts the optional parameters
  # @return [DeliveryNote]
  describe 'add_delivery_note test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_delivery_note_by_id
  # Find Delivery note by ID
  # Returns a single delivery note if the user has access
  # @param id ID of delivery note to fetch
  # @param [Hash] opts the optional parameters
  # @return [DeliveryNote]
  describe 'find_delivery_note_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_delivery_notes
  # All delivery note
  # Returns all delivery note from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<DeliveryNote>]
  describe 'find_delivery_notes test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
