=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::FixedAssetApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'FixedAssetApi' do
  before do
    # run before each test
    @instance = Beanie::FixedAssetApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FixedAssetApi' do
    it 'should create an instance of FixedAssetApi' do
      expect(@instance).to be_instance_of(Beanie::FixedAssetApi)
    end
  end

  # unit tests for add_fixed_asset
  # Creates a new fixed asset in the system
  # @param fixed_assets Fixed asset to add to the system
  # @param [Hash] opts the optional parameters
  # @return [FixedAsset]
  describe 'add_fixed_asset test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_fixed_asset_by_id
  # Find Fixed asset by ID
  # Returns a single fixed asset if the user has access
  # @param id ID of fixed asset to fetch
  # @param [Hash] opts the optional parameters
  # @return [FixedAsset]
  describe 'find_fixed_asset_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_fixed_assets
  # All fixed asset
  # Returns all fixed asset from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<FixedAsset>]
  describe 'find_fixed_assets test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
