=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::JournalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'JournalApi' do
  before do
    # run before each test
    @instance = Beanie::JournalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of JournalApi' do
    it 'should create an instance of JournalApi' do
      expect(@instance).to be_instance_of(Beanie::JournalApi)
    end
  end

  # unit tests for add_journal
  # Creates a new journal in the system
  # @param journals Journal to add to the system
  # @param [Hash] opts the optional parameters
  # @return [Journal]
  describe 'add_journal test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_journal_by_id
  # Find Journal by ID
  # Returns a single journal if the user has access
  # @param id ID of journal to fetch
  # @param [Hash] opts the optional parameters
  # @return [Journal]
  describe 'find_journal_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_journals
  # All journal
  # Returns all journal from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<Journal>]
  describe 'find_journals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
