=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::NominalAccountCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NominalAccountCategoryApi' do
  before do
    # run before each test
    @instance = Beanie::NominalAccountCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NominalAccountCategoryApi' do
    it 'should create an instance of NominalAccountCategoryApi' do
      expect(@instance).to be_instance_of(Beanie::NominalAccountCategoryApi)
    end
  end

  # unit tests for add_nominal_account_category
  # Creates a new nominal account category in the system
  # @param nominal_account_categories Nominal account category to add to the system
  # @param [Hash] opts the optional parameters
  # @return [NominalAccountCategory]
  describe 'add_nominal_account_category test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_nominal_account_categories
  # All nominal account category
  # Returns all nominal account category from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<NominalAccountCategory>]
  describe 'find_nominal_account_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_nominal_account_category_by_id
  # Find Nominal account category by ID
  # Returns a single nominal account category if the user has access
  # @param id ID of nominal account category to fetch
  # @param [Hash] opts the optional parameters
  # @return [NominalAccountCategory]
  describe 'find_nominal_account_category_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
