=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::NominalAccountApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'NominalAccountApi' do
  before do
    # run before each test
    @instance = Beanie::NominalAccountApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of NominalAccountApi' do
    it 'should create an instance of NominalAccountApi' do
      expect(@instance).to be_instance_of(Beanie::NominalAccountApi)
    end
  end

  # unit tests for add_nominal_account
  # Creates a new nominal account in the system
  # @param nominal_accounts Nominal account to add to the system
  # @param [Hash] opts the optional parameters
  # @return [NominalAccount]
  describe 'add_nominal_account test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_nominal_account_by_id
  # Find Nominal account by ID
  # Returns a single nominal account if the user has access
  # @param id ID of nominal account to fetch
  # @param [Hash] opts the optional parameters
  # @return [NominalAccount]
  describe 'find_nominal_account_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_nominal_accounts
  # All nominal account
  # Returns all nominal account from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<NominalAccount>]
  describe 'find_nominal_accounts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
