=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::PartnerAddressApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PartnerAddressApi' do
  before do
    # run before each test
    @instance = Beanie::PartnerAddressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PartnerAddressApi' do
    it 'should create an instance of PartnerAddressApi' do
      expect(@instance).to be_instance_of(Beanie::PartnerAddressApi)
    end
  end

  # unit tests for add_partner_address
  # Creates a new partner address in the system
  # @param partner_addresses Partner address to add to the system
  # @param [Hash] opts the optional parameters
  # @return [PartnerAddress]
  describe 'add_partner_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_partner_address_by_id
  # Find Partner address by ID
  # Returns a single partner address if the user has access
  # @param id ID of partner address to fetch
  # @param [Hash] opts the optional parameters
  # @return [PartnerAddress]
  describe 'find_partner_address_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_partner_addresses
  # All partner address
  # Returns all partner address from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<PartnerAddress>]
  describe 'find_partner_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
