=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::ProductVariantApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductVariantApi' do
  before do
    # run before each test
    @instance = Beanie::ProductVariantApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductVariantApi' do
    it 'should create an instance of ProductVariantApi' do
      expect(@instance).to be_instance_of(Beanie::ProductVariantApi)
    end
  end

  # unit tests for add_product_variant
  # Creates a new product variant in the system
  # @param product_variants Product variant to add to the system
  # @param [Hash] opts the optional parameters
  # @return [ProductVariant]
  describe 'add_product_variant test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_product_variant_by_id
  # Find Product variant by ID
  # Returns a single product variant if the user has access
  # @param id ID of product variant to fetch
  # @param [Hash] opts the optional parameters
  # @return [ProductVariant]
  describe 'find_product_variant_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_product_variants
  # All product variant
  # Returns all product variant from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<ProductVariant>]
  describe 'find_product_variants test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
