=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::ProductionOrderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductionOrderApi' do
  before do
    # run before each test
    @instance = Beanie::ProductionOrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductionOrderApi' do
    it 'should create an instance of ProductionOrderApi' do
      expect(@instance).to be_instance_of(Beanie::ProductionOrderApi)
    end
  end

  # unit tests for add_production_order
  # Creates a new production order in the system
  # @param production_orders Production order to add to the system
  # @param [Hash] opts the optional parameters
  # @return [ProductionOrder]
  describe 'add_production_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_production_order_by_id
  # Find Production order by ID
  # Returns a single production order if the user has access
  # @param id ID of production order to fetch
  # @param [Hash] opts the optional parameters
  # @return [ProductionOrder]
  describe 'find_production_order_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_production_orders
  # All production order
  # Returns all production order from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<ProductionOrder>]
  describe 'find_production_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
