=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::ProductCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProductCategoryApi' do
  before do
    # run before each test
    @instance = Beanie::ProductCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProductCategoryApi' do
    it 'should create an instance of ProductCategoryApi' do
      expect(@instance).to be_instance_of(Beanie::ProductCategoryApi)
    end
  end

  # unit tests for add_product_category
  # Creates a new product category in the system
  # @param product_categories Product category to add to the system
  # @param [Hash] opts the optional parameters
  # @return [ProductCategory]
  describe 'add_product_category test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_product_categories
  # All product category
  # Returns all product category from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<ProductCategory>]
  describe 'find_product_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_product_category_by_id
  # Find Product category by ID
  # Returns a single product category if the user has access
  # @param id ID of product category to fetch
  # @param [Hash] opts the optional parameters
  # @return [ProductCategory]
  describe 'find_product_category_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
