=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::PurchaseOrderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PurchaseOrderApi' do
  before do
    # run before each test
    @instance = Beanie::PurchaseOrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PurchaseOrderApi' do
    it 'should create an instance of PurchaseOrderApi' do
      expect(@instance).to be_instance_of(Beanie::PurchaseOrderApi)
    end
  end

  # unit tests for add_purchase_order
  # Creates a new purchase order in the system
  # @param purchase_orders Purchase order to add to the system
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrder]
  describe 'add_purchase_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_purchase_order_by_id
  # Find Purchase order by ID
  # Returns a single purchase order if the user has access
  # @param id ID of purchase order to fetch
  # @param [Hash] opts the optional parameters
  # @return [PurchaseOrder]
  describe 'find_purchase_order_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_purchase_orders
  # All purchase order
  # Returns all purchase order from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<PurchaseOrder>]
  describe 'find_purchase_orders test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
