=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::SalesOrderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SalesOrderApi' do
  before do
    # run before each test
    @instance = Beanie::SalesOrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SalesOrderApi' do
    it 'should create an instance of SalesOrderApi' do
      expect(@instance).to be_instance_of(Beanie::SalesOrderApi)
    end
  end

  # unit tests for add_sales_order
  # Creates a new sales order in the system
  # @param sales_orders Sales order to add to the system
  # @param [Hash] opts the optional parameters
  # @return [SalesOrder]
  describe 'add_sales_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_sales_order
  # All sales order
  # Returns all sales order from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<SalesOrder>]
  describe 'find_sales_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_sales_order_by_id
  # Find Sales order by ID
  # Returns a single sales order if the user has access
  # @param id ID of sales order to fetch
  # @param [Hash] opts the optional parameters
  # @return [SalesOrder]
  describe 'find_sales_order_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
