=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::ShippingCentreApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ShippingCentreApi' do
  before do
    # run before each test
    @instance = Beanie::ShippingCentreApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ShippingCentreApi' do
    it 'should create an instance of ShippingCentreApi' do
      expect(@instance).to be_instance_of(Beanie::ShippingCentreApi)
    end
  end

  # unit tests for add_shipping_centre
  # Creates a new shipping centre in the system
  # @param shipping_centres Shipping centre to add to the system
  # @param [Hash] opts the optional parameters
  # @return [ShippingCentre]
  describe 'add_shipping_centre test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_shipping_centre_by_id
  # Find Shipping centre by ID
  # Returns a single shipping centre if the user has access
  # @param id ID of shipping centre to fetch
  # @param [Hash] opts the optional parameters
  # @return [ShippingCentre]
  describe 'find_shipping_centre_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_shipping_centres
  # All shipping centre
  # Returns all shipping centre from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<ShippingCentre>]
  describe 'find_shipping_centres test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
