=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::StockAdjustmentApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StockAdjustmentApi' do
  before do
    # run before each test
    @instance = Beanie::StockAdjustmentApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StockAdjustmentApi' do
    it 'should create an instance of StockAdjustmentApi' do
      expect(@instance).to be_instance_of(Beanie::StockAdjustmentApi)
    end
  end

  # unit tests for add_stock_adjustment
  # Creates a new stock adjustment in the system
  # @param stock_adjustments Stock adjustment to add to the system
  # @param [Hash] opts the optional parameters
  # @return [StockAdjustment]
  describe 'add_stock_adjustment test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_adjustment_by_id
  # Find Stock adjustment by ID
  # Returns a single stock adjustment if the user has access
  # @param id ID of stock adjustment to fetch
  # @param [Hash] opts the optional parameters
  # @return [StockAdjustment]
  describe 'find_stock_adjustment_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_adjustments
  # All stock adjustment
  # Returns all stock adjustment from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<StockAdjustment>]
  describe 'find_stock_adjustments test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
