=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::StockLocationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StockLocationApi' do
  before do
    # run before each test
    @instance = Beanie::StockLocationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StockLocationApi' do
    it 'should create an instance of StockLocationApi' do
      expect(@instance).to be_instance_of(Beanie::StockLocationApi)
    end
  end

  # unit tests for add_stock_location
  # Creates a new stock location in the system
  # @param stock_locations Stock location to add to the system
  # @param [Hash] opts the optional parameters
  # @return [StockLocation]
  describe 'add_stock_location test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_location_by_id
  # Find Stock location by ID
  # Returns a single stock location if the user has access
  # @param id ID of stock location to fetch
  # @param [Hash] opts the optional parameters
  # @return [StockLocation]
  describe 'find_stock_location_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_locations
  # All stock location
  # Returns all stock location from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<StockLocation>]
  describe 'find_stock_locations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
