=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::StockCategoryApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StockCategoryApi' do
  before do
    # run before each test
    @instance = Beanie::StockCategoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StockCategoryApi' do
    it 'should create an instance of StockCategoryApi' do
      expect(@instance).to be_instance_of(Beanie::StockCategoryApi)
    end
  end

  # unit tests for add_stock_category
  # Creates a new stock category in the system
  # @param stock_categories Stock category to add to the system
  # @param [Hash] opts the optional parameters
  # @return [StockCategory]
  describe 'add_stock_category test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_categories
  # All stock category
  # Returns all stock category from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<StockCategory>]
  describe 'find_stock_categories test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_category_by_id
  # Find Stock category by ID
  # Returns a single stock category if the user has access
  # @param id ID of stock category to fetch
  # @param [Hash] opts the optional parameters
  # @return [StockCategory]
  describe 'find_stock_category_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
