=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::StockImageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'StockImageApi' do
  before do
    # run before each test
    @instance = Beanie::StockImageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StockImageApi' do
    it 'should create an instance of StockImageApi' do
      expect(@instance).to be_instance_of(Beanie::StockImageApi)
    end
  end

  # unit tests for add_stock_image
  # Creates a new stock image in the system
  # @param stock_images Stock image to add to the system
  # @param [Hash] opts the optional parameters
  # @return [StockImage]
  describe 'add_stock_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_image_by_id
  # Find Stock image by ID
  # Returns a single stock image if the user has access
  # @param id ID of stock image to fetch
  # @param [Hash] opts the optional parameters
  # @return [StockImage]
  describe 'find_stock_image_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_stock_images
  # All stock image
  # Returns all stock image from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<StockImage>]
  describe 'find_stock_images test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
