=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::SupplierAddressApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SupplierAddressApi' do
  before do
    # run before each test
    @instance = Beanie::SupplierAddressApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SupplierAddressApi' do
    it 'should create an instance of SupplierAddressApi' do
      expect(@instance).to be_instance_of(Beanie::SupplierAddressApi)
    end
  end

  # unit tests for add_supplier_address
  # Creates a new supplier address in the system
  # @param supplier_addresses Supplier address to add to the system
  # @param [Hash] opts the optional parameters
  # @return [SupplierAddress]
  describe 'add_supplier_address test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_supplier_address_by_id
  # Find Supplier address by ID
  # Returns a single supplier address if the user has access
  # @param id ID of supplier address to fetch
  # @param [Hash] opts the optional parameters
  # @return [SupplierAddress]
  describe 'find_supplier_address_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_supplier_addresses
  # All supplier address
  # Returns all supplier address from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<SupplierAddress>]
  describe 'find_supplier_addresses test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
