=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::VatRecordApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VatRecordApi' do
  before do
    # run before each test
    @instance = Beanie::VatRecordApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VatRecordApi' do
    it 'should create an instance of VatRecordApi' do
      expect(@instance).to be_instance_of(Beanie::VatRecordApi)
    end
  end

  # unit tests for add_vat_record
  # Creates a new vat record in the system
  # @param vat_records VAT record to add to the system
  # @param [Hash] opts the optional parameters
  # @return [VatRecord]
  describe 'add_vat_record test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_vat_record_by_id
  # Find VAT record by ID
  # Returns a single vat record if the user has access
  # @param id ID of vat record to fetch
  # @param [Hash] opts the optional parameters
  # @return [VatRecord]
  describe 'find_vat_record_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_vat_records
  # All vat record
  # Returns all vat record from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<VatRecord>]
  describe 'find_vat_records test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
