=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::VatReturnApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VatReturnApi' do
  before do
    # run before each test
    @instance = Beanie::VatReturnApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VatReturnApi' do
    it 'should create an instance of VatReturnApi' do
      expect(@instance).to be_instance_of(Beanie::VatReturnApi)
    end
  end

  # unit tests for add_vat_return
  # Creates a new vat return in the system
  # @param vat_returns VAT return to add to the system
  # @param [Hash] opts the optional parameters
  # @return [VatReturn]
  describe 'add_vat_return test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_vat_return_by_id
  # Find VAT return by ID
  # Returns a single vat return if the user has access
  # @param id ID of vat return to fetch
  # @param [Hash] opts the optional parameters
  # @return [VatReturn]
  describe 'find_vat_return_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_vat_returns
  # All vat return
  # Returns all vat return from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<VatReturn>]
  describe 'find_vat_returns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
