=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::WorkCentreGroupApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WorkCentreGroupApi' do
  before do
    # run before each test
    @instance = Beanie::WorkCentreGroupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkCentreGroupApi' do
    it 'should create an instance of WorkCentreGroupApi' do
      expect(@instance).to be_instance_of(Beanie::WorkCentreGroupApi)
    end
  end

  # unit tests for add_work_centre_group
  # Creates a new work centre group in the system
  # @param work_centre_groups Work centre group to add to the system
  # @param [Hash] opts the optional parameters
  # @return [WorkCentreGroup]
  describe 'add_work_centre_group test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_work_centre_group_by_id
  # Find Work centre group by ID
  # Returns a single work centre group if the user has access
  # @param id ID of work centre group to fetch
  # @param [Hash] opts the optional parameters
  # @return [WorkCentreGroup]
  describe 'find_work_centre_group_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_work_centre_groups
  # All work centre group
  # Returns all work centre group from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<WorkCentreGroup>]
  describe 'find_work_centre_groups test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
