=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Beanie::WorkCentreApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'WorkCentreApi' do
  before do
    # run before each test
    @instance = Beanie::WorkCentreApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of WorkCentreApi' do
    it 'should create an instance of WorkCentreApi' do
      expect(@instance).to be_instance_of(Beanie::WorkCentreApi)
    end
  end

  # unit tests for add_work_centre
  # Creates a new work centre in the system
  # @param work_centres Work centre to add to the system
  # @param [Hash] opts the optional parameters
  # @return [WorkCentre]
  describe 'add_work_centre test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_work_centre_by_id
  # Find Work centre by ID
  # Returns a single work centre if the user has access
  # @param id ID of work centre to fetch
  # @param [Hash] opts the optional parameters
  # @return [WorkCentre]
  describe 'find_work_centre_by_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for find_work_centres
  # All work centre
  # Returns all work centre from the system that the user has access to
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :tags tags to filter by
  # @option opts [Integer] :limit Maximum number of results to return
  # @return [Array<WorkCentre>]
  describe 'find_work_centres test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
