=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.2
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'beanie/api_client'
require 'beanie/api_error'
require 'beanie/version'
require 'beanie/configuration'

# Models
require 'beanie/models/address_block'
require 'beanie/models/bank_account_input'
require 'beanie/models/bank_statement'
require 'beanie/models/bank_statement_data'
require 'beanie/models/beanie_task'
require 'beanie/models/bill_of_material'
require 'beanie/models/billable'
require 'beanie/models/bom_item'
require 'beanie/models/company'
require 'beanie/models/delivery_note'
require 'beanie/models/delivery_note_item'
require 'beanie/models/document'
require 'beanie/models/error_model'
require 'beanie/models/fiscal_year'
require 'beanie/models/fixed_asset'
require 'beanie/models/goods_received_note'
require 'beanie/models/image'
require 'beanie/models/journal'
require 'beanie/models/journal_item'
require 'beanie/models/nominal_account'
require 'beanie/models/nominal_account_category'
require 'beanie/models/partner_address'
require 'beanie/models/partner_input'
require 'beanie/models/partner_note'
require 'beanie/models/payables_ledger'
require 'beanie/models/product'
require 'beanie/models/product_category'
require 'beanie/models/product_price'
require 'beanie/models/product_variant'
require 'beanie/models/production_order_input'
require 'beanie/models/production_order_log'
require 'beanie/models/purchase_invoice'
require 'beanie/models/purchase_order'
require 'beanie/models/purchase_order_item'
require 'beanie/models/receivables_ledger'
require 'beanie/models/sales_invoice'
require 'beanie/models/sales_invoice_item'
require 'beanie/models/sales_order'
require 'beanie/models/sales_order_item'
require 'beanie/models/shipping_centre'
require 'beanie/models/stock_adjustment'
require 'beanie/models/stock_category'
require 'beanie/models/stock_item'
require 'beanie/models/stock_location'
require 'beanie/models/stock_supplier'
require 'beanie/models/vat_record'
require 'beanie/models/vat_return'
require 'beanie/models/work_centre'
require 'beanie/models/work_centre_group'
require 'beanie/models/address_block_input'
require 'beanie/models/bank_account'
require 'beanie/models/bank_statement_data_input'
require 'beanie/models/bank_statement_input'
require 'beanie/models/beanie_task_input'
require 'beanie/models/bill_of_material_input'
require 'beanie/models/billable_input'
require 'beanie/models/bom_item_input'
require 'beanie/models/delivery_note_input'
require 'beanie/models/delivery_note_item_input'
require 'beanie/models/document_input'
require 'beanie/models/fixed_asset_input'
require 'beanie/models/goods_received_note_input'
require 'beanie/models/image_input'
require 'beanie/models/journal_input'
require 'beanie/models/journal_item_input'
require 'beanie/models/nominal_account_category_input'
require 'beanie/models/nominal_account_input'
require 'beanie/models/partner'
require 'beanie/models/partner_address_input'
require 'beanie/models/product_category_input'
require 'beanie/models/product_input'
require 'beanie/models/product_price_input'
require 'beanie/models/product_variant_input'
require 'beanie/models/production_order'
require 'beanie/models/purchase_invoice_input'
require 'beanie/models/purchase_order_input'
require 'beanie/models/purchase_order_item_input'
require 'beanie/models/sales_invoice_input'
require 'beanie/models/sales_invoice_item_input'
require 'beanie/models/sales_order_input'
require 'beanie/models/sales_order_item_input'
require 'beanie/models/shipping_centre_input'
require 'beanie/models/stock_adjustment_input'
require 'beanie/models/stock_category_input'
require 'beanie/models/stock_item_input'
require 'beanie/models/stock_location_input'
require 'beanie/models/stock_supplier_input'
require 'beanie/models/vat_record_input'
require 'beanie/models/vat_return_input'

# APIs
require 'beanie/api/address_block_api'
require 'beanie/api/bank_account_api'
require 'beanie/api/bank_statement_api'
require 'beanie/api/beanie_task_api'
require 'beanie/api/bill_of_materials_api'
require 'beanie/api/billable_api'
require 'beanie/api/company_api'
require 'beanie/api/delivery_note_api'
require 'beanie/api/document_api'
require 'beanie/api/fixed_asset_api'
require 'beanie/api/image_api'
require 'beanie/api/journal_api'
require 'beanie/api/nominal_account_api'
require 'beanie/api/nominal_account_category_api'
require 'beanie/api/partner_api'
require 'beanie/api/partner_address_api'
require 'beanie/api/product_api'
require 'beanie/api/product_category_api'
require 'beanie/api/product_price_api'
require 'beanie/api/product_variant_api'
require 'beanie/api/production_order_api'
require 'beanie/api/purchase_invoice_api'
require 'beanie/api/purchase_order_api'
require 'beanie/api/sales_invoice_api'
require 'beanie/api/sales_order_api'
require 'beanie/api/shipping_centre_api'
require 'beanie/api/stock_adjustment_api'
require 'beanie/api/stock_category_api'
require 'beanie/api/stock_item_api'
require 'beanie/api/stock_location_api'
require 'beanie/api/stock_supplier_api'
require 'beanie/api/vat_record_api'
require 'beanie/api/vat_return_api'
require 'beanie/api/work_centre_api'
require 'beanie/api/work_centre_group_api'

module Beanie
  class << self
    # Customize default settings for the SDK using block.
    #   Beanie.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
