=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.1
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'beanie/api_client'
require 'beanie/api_error'
require 'beanie/version'
require 'beanie/configuration'

# Models
require 'beanie/models/bank_account'
require 'beanie/models/error_model'
require 'beanie/models/bank_account_input'

# APIs
require 'beanie/api/bank_account_api'

module Beanie
  class << self
    # Customize default settings for the SDK using block.
    #   Beanie.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
