=begin
#Beanie ERP API

#An API specification for interacting with the Beanie ERP system

OpenAPI spec version: 0.1
Contact: dev@bean.ie
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'beanie/api_client'
require 'beanie/api_error'
require 'beanie/version'
require 'beanie/configuration'

# Models
require 'beanie/models/address_block'
require 'beanie/models/bank_account'
require 'beanie/models/bank_statement'
require 'beanie/models/bank_statement_data'
require 'beanie/models/beanie_task'
require 'beanie/models/bill_of_material'
require 'beanie/models/billable'
require 'beanie/models/bom_item'
require 'beanie/models/company'
require 'beanie/models/config_value'
require 'beanie/models/customer'
require 'beanie/models/customer_address'
require 'beanie/models/customer_ledger'
require 'beanie/models/customer_note'
require 'beanie/models/delivery_note'
require 'beanie/models/delivery_note_item'
require 'beanie/models/document'
require 'beanie/models/error_model'
require 'beanie/models/fixed_asset'
require 'beanie/models/journal'
require 'beanie/models/journal_item'
require 'beanie/models/nominal_account'
require 'beanie/models/nominal_account_category'
require 'beanie/models/product'
require 'beanie/models/product_category'
require 'beanie/models/product_price'
require 'beanie/models/product_variant'
require 'beanie/models/production_order'
require 'beanie/models/production_order_log'
require 'beanie/models/purchase_invoice'
require 'beanie/models/purchase_order'
require 'beanie/models/purchase_order_item'
require 'beanie/models/received_goods'
require 'beanie/models/sales_invoice'
require 'beanie/models/sales_invoice_item'
require 'beanie/models/sales_order'
require 'beanie/models/sales_order_item'
require 'beanie/models/shipping_centre'
require 'beanie/models/stock_adjustment'
require 'beanie/models/stock_category'
require 'beanie/models/stock_image'
require 'beanie/models/stock_item'
require 'beanie/models/stock_location'
require 'beanie/models/stock_supplier'
require 'beanie/models/supplier'
require 'beanie/models/supplier_address'
require 'beanie/models/supplier_note'
require 'beanie/models/tax_registration'
require 'beanie/models/vat_record'
require 'beanie/models/vat_return'
require 'beanie/models/work_centre'
require 'beanie/models/work_centre_group'
require 'beanie/models/address_block_input'
require 'beanie/models/bank_account_input'
require 'beanie/models/bank_statement_data_input'
require 'beanie/models/bank_statement_input'
require 'beanie/models/beanie_task_input'
require 'beanie/models/bill_of_material_input'
require 'beanie/models/billable_input'
require 'beanie/models/bom_item_input'
require 'beanie/models/company_input'
require 'beanie/models/config_value_input'
require 'beanie/models/customer_address_input'
require 'beanie/models/customer_input'
require 'beanie/models/customer_ledger_input'
require 'beanie/models/customer_note_input'
require 'beanie/models/delivery_note_input'
require 'beanie/models/delivery_note_item_input'
require 'beanie/models/document_input'
require 'beanie/models/fixed_asset_input'
require 'beanie/models/journal_input'
require 'beanie/models/journal_item_input'
require 'beanie/models/nominal_account_category_input'
require 'beanie/models/nominal_account_input'
require 'beanie/models/product_category_input'
require 'beanie/models/product_input'
require 'beanie/models/product_price_input'
require 'beanie/models/product_variant_input'
require 'beanie/models/production_order_input'
require 'beanie/models/production_order_log_input'
require 'beanie/models/purchase_invoice_input'
require 'beanie/models/purchase_order_input'
require 'beanie/models/purchase_order_item_input'
require 'beanie/models/received_goods_input'
require 'beanie/models/sales_invoice_input'
require 'beanie/models/sales_invoice_item_input'
require 'beanie/models/sales_order_input'
require 'beanie/models/sales_order_item_input'
require 'beanie/models/shipping_centre_input'
require 'beanie/models/stock_adjustment_input'
require 'beanie/models/stock_category_input'
require 'beanie/models/stock_image_input'
require 'beanie/models/stock_item_input'
require 'beanie/models/stock_location_input'
require 'beanie/models/stock_supplier_input'
require 'beanie/models/supplier_address_input'
require 'beanie/models/supplier_input'
require 'beanie/models/supplier_note_input'
require 'beanie/models/tax_registration_input'
require 'beanie/models/vat_record_input'
require 'beanie/models/vat_return_input'
require 'beanie/models/work_centre_group_input'
require 'beanie/models/work_centre_input'

# APIs
require 'beanie/api/bank_account_api'

module Beanie
  class << self
    # Customize default settings for the SDK using block.
    #   Beanie.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
